import { NewsletterData } from '../commonModels/NewsletterData';

/**
 * This data is copied from NYT graphQl api that is used by https://www.nytimes.com/newsletters
 * 
 */
export const newsletters: NewsletterData[] = [
  {
    newsletterId: 'NN',
    slug: 'morning-briefing',
    title: 'The Morning',
    caption:
      'Make sense of the day’s news and ideas. David Leonhardt and Times journalists guide you through what’s happening — and why it matters.',
    altText: 'the morning newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/NN_sample.html',
    figureImageUrl:
      'https://static.nytimes.com/email-images/newsletters/TheMorning/TheMorning-SignUp-Artwork%402x.png',
    titleImage:
      'https://static.nytimes.com/email-images/newsletters/TheMorning/NYT-ConfEmail-SignUp-Header-TheMorning.png',
    altTextLogo: 'the morning',
    titleFont: 'karn',
    frequency: 'Daily',
    thumbImageUrl: 'https://static.nytimes.com/email-images/newsletters/TheMorning/TheMorning-Icon.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpOTg==',
  },
  {
    newsletterId: 'CSB',
    slug: 'coronavirus-schools-briefing',
    title: 'Coronavirus Schools Briefing',
    caption:
      'The pandemic is upending education. Get the latest news and tips as students go back to school.',
    altText: 'Coronavirus Schools Briefing',
    sampleUrl: 'https://static.nytimes.com/email-content/CSB_sample.html',
    figureImageUrl:
      'https://static.nytimes.com/email-images/newsletters/coronavirus-schools-briefing/NYT-CoronaSchools-SignUp-Artwork-REV2.jpg',
    titleImage:
      'https://static.nytimes.com/email-images/newsletters/coronavirus-schools-briefing/NYT-CoronavirusSchools-Header-SignUp-Rev.png',
    altTextLogo: 'Coronavirus Schools Briefing',
    titleFont: 'karn',
    frequency: 'Three Times a Week',
    thumbImageUrl:
      'https://static.nytimes.com/email-images/newsletters/coronavirus-schools-briefing/NYT-Coronavirus-Schools-Icon-REV.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpDU0I=',
  },
  {
    newsletterId: 'CB',
    slug: 'coronavirus-briefing',
    title: 'Coronavirus Briefing',
    caption:
      'An informed guide to the global outbreak, with the latest developments and expert advice about prevention and treatment.',
    altText: 'Coronavirus Briefing',
    sampleUrl: 'https://static.nytimes.com/email-content/CB_sample.html',
    figureImageUrl:
      'https://static.nytimes.com/email-images/newsletters/coronavirus-briefing/Coronavirus-Signup-wIcon%402x%20(1).png',
    titleImage:
      'https://static.nytimes.com/email-images/newsletters/coronavirus-briefing/CoronavirusBriefing.png',
    altTextLogo: 'Coronavirus Briefing',
    titleFont: 'karn',
    frequency: 'Weekdays',
    thumbImageUrl:
      'https://static.nytimes.com/email-images/newsletters/coronavirus-briefing/NYT-CoronavirsuBriefing-Icon.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpDQg==',
  },
  {
    newsletterId: 'CN',
    slug: 'politics',
    title: 'On Politics With Lisa Lerer',
    caption:
      'A guide to the political news cycle, cutting through the spin and delivering clarity from the chaos.',
    altText: 'on politics with lisa lerer',
    sampleUrl: 'https://static.nytimes.com/email-content/CN_sample.html',
    figureImageUrl:
      'https://static.nytimes.com/email-images/newsletters/on-politics/OnPolitics-wicon-2020%402x.png',
    titleImage:
      'https://storage.googleapis.com/nyt-newsletter-assets-hamburger/email-images/newsletters/on-politics/newheader.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekdays',
    thumbImageUrl: 'https://static01.nytimes.com/email-images/Newsletter%20Icons/LisaLerer-OnPolitics.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpDTg==',
  },
  {
    newsletterId: 'NA',
    slug: 'breakingnewsalerts',
    title: 'Breaking News',
    caption: 'Get informed as important news breaks around the world.',
    altText: 'breaking news alerts',
    sampleUrl: 'https://static.nytimes.com/email-content/NA_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/Breaking-News/New-Breaking.png',
    titleImage: 'https://static.nytimes.com/email-images/TransparentBar_PNG.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'As Needed',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Breaking.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpOQQ==',
  },
  {
    newsletterId: 'TS',
    slug: 'great-read',
    title: 'The Great Read',
    caption:
      'Every weekday, we recommend one piece of exceptional writing from The Times — a narrative or essay that takes you someplace you might not expect to go.',
    altText: 'The Great Read',
    sampleUrl: 'https://static.nytimes.com/email-content/TS_sample.html',
    figureImageUrl:
      'https://static.nytimes.com/email-images/newsletters/Great-Read/TheGreatRead-SignUp-wIcon%402x.jpg',
    titleImage: 'https://static.nytimes.com/email-images/newsletters/Great-Read/TheGreatRead-Header.png',
    altTextLogo: 'The Great Read',
    titleFont: 'karn',
    frequency: 'Weekdays',
    thumbImageUrl: 'https://static.nytimes.com/email-images/newsletters/Great-Read/NYT-TheGreatRead-Icon.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpUUw==',
  },
  {
    newsletterId: 'TH',
    slug: 'todaysheadlines',
    title: "Today's Headlines",
    caption:
      'It’s like the print paper, but in your inbox. Wake up each morning to the day’s top headlines, organized by section.',
    altText: 'todays headlines',
    sampleUrl: 'https://static.nytimes.com/email-content/TH_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/latest-news.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Todays_Headlines.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Daily',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/TheHeadlines3.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpUSA==',
  },
  {
    newsletterId: 'NE',
    slug: 'evening-briefing',
    title: 'Evening Briefing',
    caption: 'The 10 most important things that happened today.',
    altText: 'the evening briefing newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/NE_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/evening-briefing.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Evening_Briefing.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekdays',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Evening-Briefing.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpORQ==',
  },
  {
    newsletterId: 'MBAE',
    slug: 'morning-briefing-asia',
    title: 'Morning Briefing: Asia Edition',
    caption: 'What you need to know to start your day, delivered to your inbox.',
    altText: 'morning briefing asia',
    sampleUrl: 'https://static.nytimes.com/email-content/MBAE_sample.html',
    figureImageUrl:
      'https://static.nytimes.com/email-images/newsletters/briefings/MorningBriefing-wicon%402x.jpg',
    titleImage: null,
    altTextLogo: null,
    titleFont: 'frank',
    frequency: 'Weekdays',
    thumbImageUrl: 'https://static01.nytimes.com/email-images/newsletters/briefings/AM-Asia.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpNQkFF',
  },
  {
    newsletterId: 'MBAU',
    slug: 'morning-briefing-australia',
    title: 'Morning Briefing: Australia Edition',
    caption: 'What you need to know to start your day, delivered to your inbox.',
    altText: 'morning briefing australia',
    sampleUrl: 'https://static.nytimes.com/email-content/MBAU_sample.html',
    figureImageUrl:
      'https://static.nytimes.com/email-images/newsletters/briefings/MorningBriefing-wicon%402x.jpg',
    titleImage: null,
    altTextLogo: null,
    titleFont: 'frank',
    frequency: 'Weekdays',
    thumbImageUrl: 'https://static01.nytimes.com/email-images/newsletters/briefings/AM-Australia.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpNQkFV',
  },
  {
    newsletterId: 'MBE',
    slug: 'morning-briefing-europe',
    title: 'Morning Briefing: Europe Edition',
    caption: 'Get what you need to know to start your day, delivered to your inbox.',
    altText: 'morning briefing',
    sampleUrl: 'https://static.nytimes.com/email-content/MBE_sample.html',
    figureImageUrl:
      'https://static.nytimes.com/email-images/newsletters/briefings/MorningBriefing-wicon%402x.jpg',
    titleImage: null,
    altTextLogo: 'morning briefing',
    titleFont: 'frank',
    frequency: 'Weekdays',
    thumbImageUrl: 'https://static01.nytimes.com/email-images/newsletters/briefings/AM-Europe.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpNQkU=',
  },
  {
    newsletterId: 'YWP',
    slug: 'your-weekly-edition',
    title: 'Your Weekly Edition',
    caption: 'A selection of stories published in the last week and personalized for you.',
    altText: 'your weekly edition newsletter',
    sampleUrl: null,
    figureImageUrl: 'https://static01.nytimes.com/email-images/newsletters/Your-Weekly-Edition/GIF2.gif',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Your_Weekly_Edition_Header.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Your-Weekly-Edition.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpZV1A=',
  },
  {
    newsletterId: 'GN',
    slug: 'in-her-words',
    title: 'In Her Words',
    caption: 'Where women rule the headlines.',
    altText: 'In Her Words',
    sampleUrl: 'https://static.nytimes.com/email-content/GN_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/gender-issues/InHerWords2.jpg',
    titleImage: 'https://static01.nyt.com/email-images/newsletters/In_Her_Words/header.png',
    altTextLogo: 'In Her Words',
    titleFont: 'karn',
    frequency: 'Three times a week',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/In-Her-Words.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpHTg==',
  },
  {
    newsletterId: 'DY',
    slug: 'the-daily',
    title: 'The Daily',
    caption:
      'An exclusive look at how one of the week’s biggest stories came together on “The Daily” podcast.',
    altText: 'The Daily',
    sampleUrl: 'https://static.nytimes.com/email-content/DY_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/TheDaily/The%20Daily.png',
    titleImage: 'https://static.nytimes.com/email-images/newsletters/TheDaily/The_Daily.png',
    altTextLogo: 'The Daily',
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/The-Daily.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpEWQ==',
  },
  {
    newsletterId: 'WAR',
    slug: 'at-war',
    title: 'At War',
    caption:
      'A weekly roundup of news related to current conflicts, civil unrest and military action around the world.',
    altText: 'At War',
    sampleUrl: 'https://static.nytimes.com/email-content/WAR_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/atwar/NYT-AtWar-SignUpArt%402x.png',
    titleImage: null,
    altTextLogo: 'At War',
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static.nytimes.com/email-images/newsletters/atwar/NYT-AtWar-Icon.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpXQVI=',
  },
  {
    newsletterId: 'AUST',
    slug: 'australia-letter',
    title: 'Australia Letter',
    caption: 'News, features and opinion for readers in the region, plus fun local recommendations.',
    altText: 'australia-letter',
    sampleUrl: 'https://static.nytimes.com/email-content/AUST_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/Australia-Letter/AUS%20Letter.png',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Australia_Letter.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/AUS-Letter.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpBVVNU',
  },
  {
    newsletterId: 'CLIM',
    slug: 'climate-change',
    title: 'Climate Fwd:',
    caption:
      'What on earth is going on? The latest news about climate change, plus tips on how you can help.',
    altText: 'climate fwd, stories about climate change',
    sampleUrl: 'https://static.nytimes.com/email-content/CLIM_sample.html',
    figureImageUrl: 'https://static01.nyt.com/email-images/newsletters/climate/Climate.png',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Climate_Fwd.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Climate.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpDTElN',
  },
  {
    newsletterId: 'MSB',
    slug: 'marc-stein',
    title: 'Marc Stein On Basketball',
    caption:
      'Exclusive commentary and reporting from a Hall of Fame sportswriter, who has covered everyone from Magic to Michael to LeBron.',
    altText: 'Marc Stein',
    sampleUrl: 'https://static.nytimes.com/email-content/MSB_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/sports/MStein2-394.png',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Marc_Stein.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/MarcStein.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpNU0I=',
  },
  {
    newsletterId: 'RS',
    slug: 'rory-smith',
    title: 'Rory Smith On Soccer',
    caption: 'One of the world’s best commentators analyzes tactics, matches and personalities.',
    altText: null,
    sampleUrl: 'https://static.nytimes.com/email-content/RS_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/RorySmith/Smith%2CRory.png',
    titleImage: 'https://static01.nytimes.com/email-images/newsletters/RorySmith/RorySmith_OnSoccer.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/RorySmith.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpSUw==',
  },
  {
    newsletterId: 'CA',
    slug: 'california-today',
    title: 'California Today',
    caption: 'Top news and features from across one of America’s largest and most dynamic states.',
    altText: 'california today',
    sampleUrl: 'https://static.nytimes.com/email-content/CA_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/CA-Today/CA%20Today.png',
    titleImage: 'https://static01.nyt.com/email-images/California_Today.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekdays',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/CA-Today.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpDQQ==',
  },
  {
    newsletterId: 'CNDA',
    slug: 'canada-letter',
    title: 'Canada Letter',
    caption:
      'Back stories and analysis from our Canadian correspondents, plus a handpicked selection of our recent Canada-related coverage.',
    altText: 'canada letter',
    sampleUrl: 'https://static.nytimes.com/email-content/CNDA_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/Canada-Letter/CAN%20Letter.png',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Canada_Letter.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/CAN-Letter.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpDTkRB',
  },
  {
    newsletterId: 'INT',
    slug: 'the-interpreter',
    title: 'The Interpreter',
    caption:
      'Subscribe for original insights, commentary and discussions on the major news stories of the week, from columnists Max Fisher and Amanda Taub.',
    altText: 'the interpreter',
    sampleUrl: 'https://static.nytimes.com/email-content/INT_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/theinterpreter_396.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/The_Interpreter.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/The-Interpreter.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpJTlQ=',
  },
  {
    newsletterId: 'UR',
    slug: 'newyorktoday',
    title: 'New York Today',
    caption:
      'Local reporting on the stories that define the city. Plus weather, upcoming events, Metropolitan Diary and more.',
    altText: 'new york today newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/UR_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/New-York-Today/NY%20Today.png',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/New_York_Today.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Daily',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/NY-Today.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpVUg==',
  },
  {
    newsletterId: 'MA',
    slug: 'magazine',
    title: 'The New York Times Magazine',
    caption:
      'Get the best of each issue with long reads, cover stories and columns like The Ethicist, Diagnosis and Eat.',
    altText: 'the new york times magazine',
    sampleUrl: 'https://static.nytimes.com/email-content/MA_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/new-york-times-magazine.jpg',
    titleImage: 'https://static01.nyt.com/email-images/NYT_Mag_Newsletter_Header.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/NYTMag.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpNQQ==',
  },
  {
    newsletterId: 'RR',
    slug: 'race-related',
    title: 'Race/Related',
    caption: 'Explore the countless ways race affects our lives, with provocative reporting and discussion.',
    altText: 'race related',
    sampleUrl: 'https://static.nytimes.com/email-content/RR_sample.html',
    figureImageUrl:
      'https://static.nytimes.com/email-images/newsletters/racerelated/rr-signup-articleLarge-v2.gif',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Race_Related.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/RaceRelated.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpSUg==',
  },
  {
    newsletterId: 'SP',
    slug: 'sports',
    title: 'Sports',
    caption: 'Get our most ambitious projects, stories and analysis delivered to your inbox every week.',
    altText: 'sports newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/SP_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/sports/image.png',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Sports.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Sports.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpTUA==',
  },
  {
    newsletterId: 'SC',
    slug: 'science-times',
    title: 'Science Times',
    caption: 'Get stories that capture the wonders of nature, the cosmos and the human body.',
    altText: 'science times',
    sampleUrl: 'https://static.nytimes.com/email-content/SC_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/science_news.png',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Science_Times.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/ScienceTimes.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpTQw==',
  },
  {
    newsletterId: 'UP',
    slug: 'upshot',
    title: 'The Upshot',
    caption:
      'Analysis that explains politics, policy and everyday life, with an emphasis on data and charts.',
    altText: 'the upshot newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/UP_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/upshot.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/The_Upshot.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Twice a Week',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/The-Upshot.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpVUA==',
  },
  {
    newsletterId: 'BN',
    slug: 'el-times',
    title: 'El Times',
    caption:
      'Una  selección semanal de historias en español que no encontrarás en ningún otro sitio, con eñes y acentos.',
    altText: 'el times newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/BN_sample.html',
    figureImageUrl: 'https://static01.nytimes.com/email-images/newsletters/el-times/ElTimes.png',
    titleImage: 'https://static.nytimes.com/email-images/TransparentBar_PNG.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Twice a Week',
    thumbImageUrl: 'https://static01.nytimes.com/email-images/newsletters/el-times/ElTimes.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpCTg==',
  },
  {
    newsletterId: 'CNB',
    slug: 'chinese-briefing',
    title: '新闻简报',
    caption:
      '订阅每日精选新闻简报，《纽约时报》的全球报道会直接送达您的电子邮箱，包括国际和中国时事、教育、科技、健康、观点与评论等精彩内容。',
    altText: null,
    sampleUrl: 'https://cn.nytimes.com/morning-brief/',
    figureImageUrl:
      'https://static01.nyt.com/images/2017/06/21/world/21DC-TRUMPCHINA/21DC-TRUMPCHINA-articleLarge.jpg',
    titleImage: 'https://sso.nytcn.me/img/logo-s.gif',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: '周一至周五',
    thumbImageUrl:
      'https://static01.nyt.com/images/2017/06/21/world/21DC-TRUMPCHINA/21DC-TRUMPCHINA-square320.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpDTkI=',
  },
  {
    newsletterId: 'DB',
    slug: 'debatable',
    title: 'Debatable',
    caption:
      'Agree to disagree, or disagree better? Broaden your perspective with sharp arguments on the most pressing issues of the week.',
    altText: null,
    sampleUrl: 'https://static.nytimes.com/email-content/DB_sample.html',
    figureImageUrl:
      'https://static01.nyt.com/images/2019/08/28/opinion/debatable-signup/debatable-signup-popup.png',
    titleImage: 'https://static01.nytimes.com/email-images/newsletters/kristof/WhiteBar_PNG.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Twice a Week',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Debatable.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpEQg==',
  },
  {
    newsletterId: 'TY',
    slug: 'opinion-todaynl',
    title: 'Opinion Today',
    caption: 'Get expert analysis of the news and a guide to the big ideas shaping the world. ',
    altText: 'Opinion Today newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/TY_sample.html',
    figureImageUrl:
      'https://static01.nyt.com/images/2020/05/01/opinion/Opinion-Today-sign-up/Opinion-Today-sign-up-articleLarge.png',
    titleImage:
      'https://static01.nyt.com/images/2020/05/01/opinion/Opinion-Today-hed/Opinion-Today-hed-popup.png',
    altTextLogo: null,
    titleFont: 'chelt',
    frequency: 'Weekdays',
    thumbImageUrl:
      'https://static01.nyt.com/images/2020/05/01/opinion/Opinion-Today-thumb/Opinion-Today-thumb-articleLarge.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpUWQ==',
  },
  {
    newsletterId: 'NK',
    slug: 'nicholas-kristof',
    title: 'Nicholas Kristof',
    caption:
      "Get a behind-the-scenes look at Nick's gritty journalism as he travels around the United States and the world.",
    altText: null,
    sampleUrl: 'https://static.nytimes.com/email-content/NK_sample.html',
    figureImageUrl:
      'https://static01.nyt.com/images/2019/02/04/opinion/kristof-new-signup/kristof-new-signup-popup.png',
    titleImage: 'https://static01.nytimes.com/email-images/newsletters/kristof/WhiteBar_PNG.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Twice a Week',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/NicholasKristof.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpOSw==',
  },
  {
    newsletterId: 'JBO',
    slug: 'jamellebouie',
    title: 'Jamelle Bouie',
    caption:
      'Discover overlooked writing from around the internet, plus get exclusive thoughts, photos and reading recommendations from Jamelle.',
    altText: null,
    sampleUrl: 'https://static.nytimes.com/email-content/JBO_sample.html',
    figureImageUrl:
      'https://static01.nyt.com/images/2019/01/31/opinion/Jamelle-sign-up/Jamelle-sign-up-popup.png',
    titleImage: 'https://static01.nytimes.com/email-images/newsletters/kristof/WhiteBar_PNG.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/JamelleBouie.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpKQk8=',
  },
  {
    newsletterId: 'PK',
    slug: 'paul-krugman',
    title: 'Paul Krugman',
    caption: "Get a better understanding of the economy — and an even deeper look inside Paul's mind.",
    altText: null,
    sampleUrl: 'https://static.nytimes.com/email-content/PK_sample.html',
    figureImageUrl:
      'https://static01.nyt.com/images/2019/02/14/opinion/krugman-signup/krugman-signup-popup.png',
    titleImage: 'https://static01.nytimes.com/email-images/newsletters/kristof/WhiteBar_PNG.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/PaulKrugman.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpQSw==',
  },
  {
    newsletterId: 'FB',
    slug: 'frank-bruni',
    title: 'Frank Bruni',
    caption:
      "Get a more personal take on politics, newsmakers and more with Frank's exclusive commentary every week.",
    altText: 'Frank Bruni',
    sampleUrl: 'https://static.nytimes.com/email-content/FB_sample.html',
    figureImageUrl:
      'https://static01.nytimes.com/email-images/newsletters/frank-bruni/FrankBruni_396x264_PNG.png',
    titleImage: 'https://static01.nytimes.com/email-images/newsletters/kristof/WhiteBar_PNG.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/FrankBruni.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpGQg==',
  },
  {
    newsletterId: 'OWR',
    slug: 'sunday-best',
    title: 'Sunday Best',
    caption:
      'Never be uninteresting. Read the most thought-provoking, funny, delightful and raw stories from The New York Times Opinion section.',
    altText: 'Sunday Best',
    sampleUrl: 'https://static.nytimes.com/email-content/OWR_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/sunday-best/Sunday%20Best.png',
    titleImage: 'https://static.nytimes.com/email-images/TransparentBar_PNG.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/SundayBest-NoType.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpPV1I=',
  },
  {
    newsletterId: 'OD',
    slug: 'opdocs',
    title: 'Op-Docs',
    caption: 'Watch Oscar-nominated short documentaries from around the world, sent straight to your inbox.',
    altText: 'op-docs',
    sampleUrl: 'https://static.nytimes.com/email-content/OD_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/opdocs.jpg',
    titleImage: 'https://static01.nyt.com/packages/images/email/assets/logos/op-docs.png',
    altTextLogo: 'op docs',
    titleFont: 'karn',
    frequency: 'Bi-Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/OpDocs.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpPRA==',
  },
  {
    newsletterId: 'OT',
    slug: 'on-tech',
    title: 'On Tech with Shira Ovide',
    caption: 'Your guide to how technology is transforming our lives and the world.',
    altText: 'On Tech With Shira Ovide',
    sampleUrl: 'https://static.nytimes.com/email-content/OT_sample.html',
    figureImageUrl:
      'https://static.nytimes.com/email-images/newsletters/On-Tech/OnTech-SignUp-wIcon%402x.jpg',
    titleImage:
      'https://static.nytimes.com/email-images/newsletters/On-Tech/OnTech-WithShiraOvide-Header.png',
    altTextLogo: 'On Tech With Shira Ovide',
    titleFont: 'karn',
    frequency: 'Weekdays',
    thumbImageUrl: 'https://static01.nytimes.com/email-images/Newsletter%20Icons/ShiraOvide-OnTech.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpPVA==',
  },
  {
    newsletterId: 'DK',
    slug: 'dealbook',
    title: 'DealBook',
    caption: 'The most crucial business and policy news you need to know from Andrew Ross Sorkin and team.',
    altText: 'dealbook newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/DK_sample.html',
    figureImageUrl:
      'https://static.nytimes.com/email-images/newsletters/DealBook/DealBook-2020-wIcon%402x.jpg',
    titleImage: 'https://static.nytimes.com/email-images/newsletters/DealBook/NYT-Nwsltr-DealBook-Header.png',
    altTextLogo: 'dealbook',
    titleFont: 'karn',
    frequency: 'Weekdays',
    thumbImageUrl: 'https://static.nytimes.com/email-images/newsletters/DealBook/NYT-Icon-DealBook.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpESw==',
  },
  {
    newsletterId: 'WIN',
    slug: 'with-interest',
    title: 'With Interest',
    caption:
      'Catch up and prep for the week ahead with this newsletter of the most important business insights, delivered Sundays.\n',
    altText: 'with interest newsletter',
    sampleUrl: ' https://static.nytimes.com/email-content/WIN_sample.html',
    figureImageUrl: 'https://static01.nytimes.com/email-images/newsletters/with-interest/396x264.jpg',
    titleImage: 'https://static.nytimes.com/email-images/With-Interest.png',
    altTextLogo: 'with interest newsletter',
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/WithInterest.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpXSU4=',
  },
  {
    newsletterId: 'WS',
    slug: 'wheels',
    title: 'Wheels',
    caption:
      'Every third Tuesday of the month, get the news, trends, car reviews and more from the Wheels newsletter',
    altText: 'wheels newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/WS_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/auto-news.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Wheels.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Monthly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Wheels.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpXUw==',
  },
  {
    newsletterId: 'MY',
    slug: 'yourmoney',
    title: 'Your Money',
    caption:
      'Every week, get tips on retirement, paying for college, credit cards and the right way to invest.',
    altText: 'your money newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/MY_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/financial-advice.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Your_Money.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/YourMoney.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpNWQ==',
  },
  {
    newsletterId: 'AH',
    slug: 'at-home',
    title: 'At Home',
    caption: 'Our best suggestions for how to live a full and cultured life during the pandemic, at home.',
    altText: 'At Home',
    sampleUrl: 'https://static.nytimes.com/email-content/AH_sample.html',
    figureImageUrl:
      'https://static.nytimes.com/email-images/newsletters/AtHome/AtHome-SignUp-Artwork-1000px-REV.png',
    titleImage: 'https://static.nytimes.com/email-images/newsletters/AtHome/NYT-SignUp-Header-AtHome.png',
    altTextLogo: 'At Home',
    titleFont: 'karn',
    frequency: 'Twice a Week',
    thumbImageUrl: 'https://static.nytimes.com/email-images/newsletters/AtHome/NYT-AtHome-Icon-REV.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpBSA==',
  },
  {
    newsletterId: 'LI',
    slug: 'wait',
    title: 'Wait ...',
    caption: 'How technology and celebrity are changing our lives — for better and for worse.',
    altText: 'Wait ...',
    sampleUrl: 'https://static.nytimes.com/email-content/LI_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/Wait/New-Wait.png',
    titleImage: 'https://static.nytimes.com/email-images/newsletters/Wait.../Wait-REV-01.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Twice a week',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Wait.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpMSQ==',
  },
  {
    newsletterId: 'PTG',
    slug: 'parenting',
    title: 'NYT Parenting',
    caption: 'Get evidence-based guidance, plus personal stories and tiny victories from other parents.',
    altText: 'Parenting',
    sampleUrl: 'https://static.nytimes.com/email-content/PTG_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/Parenting/396X264-%402x.png',
    titleImage: 'https://static.nytimes.com/email-images/TransparentBar_PNG.png',
    altTextLogo: 'Parenting',
    titleFont: 'karn',
    frequency: 'Twice a Week',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Parenting.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpQVEc=',
  },
  {
    newsletterId: 'FWD',
    slug: 'five-weeknight-dishes',
    title: 'Five Weeknight Dishes',
    caption: 'Fresh, delicious dinner ideas for busy people, from Emily Weinstein and NYT Cooking.',
    altText: 'five weeknight dishes newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/FWD_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/FiveWeeknightDishes/New-Five.png',
    titleImage:
      'https://static.nytimes.com/email-images/newsletters/FiveWeeknightDishes/FiveWeeknightDishes_NewsletterSignUp.png',
    altTextLogo: 'five weeknight dishes newsletter',
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Five-Weeknight-Dishes.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpGV0Q=',
  },
  {
    newsletterId: 'CK',
    slug: 'cooking',
    title: 'Cooking',
    caption: 'Feast on recipes, food writing and culinary inspiration from Sam Sifton and NYT Cooking.',
    altText: 'cooking newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/CK_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/cooking/Cooking.png',
    titleImage: 'https://static01.nyt.com/packages/images/email/assets/logos/Cooking_120.png',
    altTextLogo: 'cooking',
    titleFont: 'karn',
    frequency: 'Five Times a Week',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Cooking.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpDSw==',
  },
  {
    newsletterId: 'LL',
    slug: 'love-letter',
    title: 'Love Letter',
    caption: 'Real stories that examine the highs, lows and woes of relationships.',
    altText: 'Love Letter',
    sampleUrl: 'https://static.nytimes.com/email-content/LL_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/love-letter/loveletter1.png',
    titleImage: 'https://static.nytimes.com/email-images/New%20Headers/Love-Letter.png',
    altTextLogo: 'Love Letter',
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static.nytimes.com/email-images/newsletters/love-letter/loveletter1.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpMTA==',
  },
  {
    newsletterId: 'TMAG',
    slug: 't-list',
    title: 'The T List',
    caption: 'A weekly roundup of what the editors of T Magazine are noticing and coveting right now.',
    altText: 'The T List Newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/TMAG_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/t-list/newsletter_396x264.jpg',
    titleImage: 'https://static.nytimes.com/email-images/TransparentBar_PNG.png',
    altTextLogo: 'The T List Newsletter',
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/The-TList.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpUTUFH',
  },
  {
    newsletterId: 'TZ',
    slug: 'open-thread-fashion',
    title: 'Open Thread',
    caption: 'Vanessa Friedman, our chief fashion critic, delivers the latest news on what we wear.',
    altText: 'open thread',
    sampleUrl: 'https://static.nytimes.com/email-content/TZ_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/open_thread.png',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Open_Thread.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Open-Thread.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpUWg==',
  },
  {
    newsletterId: 'RU',
    slug: 'running',
    title: 'Running',
    caption: 'Hit your stride with practical tips, expert advice and new sources of motivation.',
    altText: 'running',
    sampleUrl: 'https://static.nytimes.com/email-content/RU_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/running_news.gif',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Running.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Running.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpSVQ==',
  },
  {
    newsletterId: 'SL',
    slug: 'smarter-living',
    title: 'Smarter Living',
    caption: 'Tips and advice for living a better, smarter, more fulfilling life.',
    altText: 'Smarter Living newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/SL_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/SmarterLiving/Smarter%20Living.png',
    titleImage: null,
    altTextLogo: ' ',
    titleFont: ' ',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/SmarterLiving-NoType.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpTTA==',
  },
  {
    newsletterId: 'LN',
    slug: 'thelearningnetwork',
    title: 'The Learning Network',
    caption: 'Get teaching and learning resources based on New York Times journalism.',
    altText: 'the learning network newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/LN_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/learning-resources.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Learning_Network.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/LearningNetwork.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpMTg==',
  },
  {
    newsletterId: 'TL',
    slug: 'traveldispatch',
    title: 'Travel Dispatch',
    caption:
      'Discover destinations, get tips on traveling smarter, and read regular features like 36 Hours and Frugal Traveler.',
    altText: 'travel dispatch newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/TL_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/travel-tips.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Travel_Dispatch.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/TravelDispatch.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpUTA==',
  },
  {
    newsletterId: 'HH',
    slug: 'well',
    title: 'Well',
    caption: 'Get the best of Well, with the latest on health, fitness and nutrition.',
    altText: 'well newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/HH_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/health-news.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Well.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Well.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpISA==',
  },
  {
    newsletterId: 'ML',
    slug: 'well-family',
    title: 'Well Family',
    caption:
      'Get the latest news on issues including kids’ health, homework, adolescent development, college, relationships and more.',
    altText: 'well family newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/ML_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/parental_guidance.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Well_Family.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Well-Family.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpNTA==',
  },
  {
    newsletterId: 'RE',
    slug: 'realestate',
    title: 'Real Estate',
    caption:
      'Every week, get updates on residential real estate news, covering the five boroughs and beyond.',
    altText: 'real estate newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/RE_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/real-estate-news.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Real_Estate.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Real-Estate.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpSRQ==',
  },
  {
    newsletterId: 'BK',
    slug: 'books-review',
    title: 'Books',
    caption:
      'Be the first to read books news and see reviews, news and features in The New York Times Book Review.',
    altText: 'books update newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/BK_sample.html',
    figureImageUrl: 'https://static01.nyt.com/email-images/newsletters/books/Books-REV.png',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Books.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Twice a Week',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Books-REV.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpCSw==',
  },
  {
    newsletterId: 'FM',
    slug: 'moviesupdate',
    title: 'Movies Update',
    caption: 'A weekly roundup of movie reviews, news, stars and awards-season analysis. \n',
    altText: 'movies update newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/FM_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/movies-update.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Movies_Update.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Movies-Update.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpGTQ==',
  },
  {
    newsletterId: 'MS',
    slug: 'louder',
    title: 'Louder',
    caption:
      'A once-a-week blast of pop music coverage, including album reviews, interviews with artists and playlists curated by our critics.',
    altText: 'louder',
    sampleUrl: 'https://static.nytimes.com/email-content/MS_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/louder_figure.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Louder.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Louder.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpNUw==',
  },
  {
    newsletterId: 'CU',
    slug: 'theater-update',
    title: 'Theater Update',
    caption:
      'Every week, stay on top of the top-grossing Broadway shows, recent reviews, Critics’ Picks and more.',
    altText: 'theater update newsletter',
    sampleUrl: 'https://static.nytimes.com/email-content/CU_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/broadway-news.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Theater_Update.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Theater-Update.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpDVQ==',
  },
  {
    newsletterId: 'WG',
    slug: 'watching',
    title: 'Watching',
    caption: ' Get recommendations on the best TV shows and movies to watch.',
    altText: 'watching',
    sampleUrl: 'https://static.nytimes.com/email-content/WG_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/watching/watching_sign-up.png',
    titleImage: 'https://static01.nyt.com/email-images/Watching_Color.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: 'Twice a Week',
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Watching.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpXRw==',
  },
  {
    newsletterId: 'NQ',
    slug: 'news-quiz',
    title: 'News Quiz',
    caption: 'Are you up-to-date on the headlines? Sign up to get notified when our quiz is published.',
    altText: 'News Quiz',
    sampleUrl: 'https://static.nytimes.com/email-content/NQ_sample.html',
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/news-quiz/NYT-NewsQuiz-SignUp.png',
    titleImage: 'https://static.nytimes.com/email-images/newsletters/news-quiz/TransparentBar_PNG.png',
    altTextLogo: 'News Quiz',
    titleFont: 'karn',
    frequency: null,
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/NewsQuiz-R.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpOUQ==',
  },
  {
    newsletterId: 'TTA',
    slug: 'presidents-taxes',
    title: "The President's Taxes",
    caption: 'Sign up to get notified when we publish a new article in this series.',
    altText: "The President's Taxes",
    sampleUrl: null,
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/presidents-taxes/1200x1200_t.png',
    titleImage: null,
    altTextLogo: "The President's Taxes",
    titleFont: 'frank',
    frequency: 'As Needed',
    thumbImageUrl: 'https://static.nytimes.com/email-images/newsletters/presidents-taxes/1200x1200_t.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpUVEE=',
  },
  {
    newsletterId: 'WKDR',
    slug: 'weekender',
    title: 'The Weekender',
    caption: 'Times editors handpick stories for you to enjoy each weekend.',
    altText: 'The Weekender',
    sampleUrl: null,
    figureImageUrl: 'https://static.nytimes.com/email-images/newsletters/Weekender/NYT-TheWeekender-Icon.jpg',
    titleImage: null,
    altTextLogo: 'The Weekender',
    titleFont: 'frank',
    frequency: 'Weekly',
    thumbImageUrl: 'https://static.nytimes.com/email-images/newsletters/Weekender/NYT-TheWeekender-Icon.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpXS0RS',
  },
  {
    newsletterId: 'HY',
    slug: 'sophisticatedshopper',
    title: 'Sophisticated Shopper',
    caption: 'Be the first to know about select sales, in-store promotions, new product launches and more.',
    altText: 'sophisticated shopper',
    sampleUrl: 'https://static.nytimes.com/email-content/HY_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/shopping-deals.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Sophisticated_Shopper.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: null,
    thumbImageUrl: 'https://static01.nyt.com/packages/images/email/assets/splash/sophisticated-shopper.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpIWQ==',
  },
  {
    newsletterId: 'GY',
    slug: 'greatgetaways',
    title: 'Great Getaways',
    caption: 'Find your ideal escape. Get exclusive offers from some of the world’s finest travel providers.',
    altText: 'great getaways',
    sampleUrl: 'https://static.nytimes.com/email-content/GY_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/getaway.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Great_Getaways.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: null,
    thumbImageUrl: 'https://static01.nyt.com/packages/images/email/assets/splash/great-getaways.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpHWQ==',
  },
  {
    newsletterId: 'TD',
    slug: 'traveldeals',
    title: 'Travel Deals',
    caption:
      'Every week, get exclusive hotel, airline, cruise and vacation packages delivered to your inbox.',
    altText: 'travel deals',
    sampleUrl: 'https://static.nytimes.com/email-content/TD_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/vacation-deals.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Travel_Deals.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: null,
    thumbImageUrl: 'https://static01.nyt.com/packages/images/email/assets/splash/travel-deals.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpURA==',
  },
  {
    newsletterId: 'TR',
    slug: 'ticketwatch',
    title: 'TicketWatch',
    caption: 'Receive special offers and promotions on Broadway and premier live entertainment.',
    altText: 'ticket watch special offer',
    sampleUrl: 'https://static.nytimes.com/email-content/TR_sample.html',
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/live-entertainment.jpg',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Ticket_Watch.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: null,
    thumbImageUrl: 'https://static01.nyt.com/packages/images/email/assets/splash/ticket-watch.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpUUg==',
  },
  {
    newsletterId: 'ST',
    slug: 'times-store',
    title: 'The New York Times Store',
    caption: 'Receive special offers, promotions and advance preview for curated and exclusive products.',
    altText: 'the new york times store special offer',
    sampleUrl: null,
    figureImageUrl:
      'https://a1.nyt.com/assets/newsletters/latest/images/newsletters/thumb_nails/the-new-york-times-store.jpg',
    titleImage: null,
    altTextLogo: null,
    titleFont: 'karn',
    frequency: null,
    thumbImageUrl:
      'https://static01.nyt.com/packages/images/email/assets/splash/the-new-york-times-store.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpTVA==',
  },
  {
    newsletterId: 'TJ',
    slug: 'times-journeys',
    title: 'Times Journeys',
    caption:
      'Travel with The New York Times. Get curated content and exclusive invitations to events that inspire your travels.',
    altText: 'times journeys special offer',
    sampleUrl: null,
    figureImageUrl:
      'https://a1.nyt.com/assets/newsletters/latest/images/newsletters/thumb_nails/times-journeys.jpg',
    titleImage: null,
    altTextLogo: null,
    titleFont: 'karn',
    frequency: null,
    thumbImageUrl: 'https://static01.nyt.com/packages/images/email/assets/splash/times-journeys.jpg',
    id: 'TmV3c2xldHRlckNvbmZpZzpUSg==',
  },
  {
    newsletterId: 'MM',
    slug: 'updates-and-special-offers',
    title: 'Updates and Special Offers',
    caption:
      'Stay on top of the latest New York Times events, special offers, product updates and article recommendations.',
    altText: 'updates and special offers',
    sampleUrl: null,
    figureImageUrl: 'https://static01.nyt.com/packages/images/email/assets/updates_and_special_offers.png',
    titleImage: 'https://static01.nyt.com/email-images/Karnak_Headers/Updates_and_Special_Offers.png',
    altTextLogo: null,
    titleFont: 'karn',
    frequency: null,
    thumbImageUrl:
      'https://static01.nyt.com/packages/images/email/assets/splash/updates_and_special_offers.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpNTQ==',
  },
  {
    newsletterId: 'TTT',
    slug: 'times-talks',
    title: 'New York Times Events',
    caption: 'Be the first to know about upcoming live events and virtual gatherings from The Times.',
    altText: 'Times Events',
    sampleUrl: null,
    figureImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Times-Events.png',
    titleImage: null,
    altTextLogo: 'Times Events ',
    titleFont: 'karnak',
    frequency: null,
    thumbImageUrl: 'https://static01.nyt.com/email-images/Newsletter%20Icons/Times-Events.png',
    id: 'TmV3c2xldHRlckNvbmZpZzpUVFQ=',
  },
];
